### ISSUE TITLE
Fails on import

### ISSUE THREAD

**Issue by tawe141** [Ohjeah/sparsereg#8]
```
>>> import sparsereg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\sparsereg\__init__.py", line 1, in <module>
    from sparsereg.model import *
ImportError: No module named model
>>>
```

This error occurs in Python 2.7.11 and Anaconda Python 3.6, both on Windows 10 64-bit. Any help resolving this one?

**Comment by Ohjeah** [comment]
Hi,
thanks for trying sparsereg.
The error is fixed now - I always install in developer modus and did not catch this mistake.
Please try the latest version on pip with python 3.5+

**Comment by tawe141** [comment]
Works great, thanks!
