### ISSUE TITLE
sindy.py - example bug/User error

### ISSUE THREAD

**Issue by TarenGorman** [Ohjeah/sparsereg#9]
## Expected Behavior
example\sindy.py to print score and equations.

## Actual Behavior
TypeError: 'tuple' object does not support item assignment
### Screenshot of traceback
[http://imgur.com/a/s2Ph3](url)

### In ipython console
  1. runfile('../sparsereg-master/example/sindy.py', wdir='../sparsereg-master/example')
### In powershell
  1. cd to '../sparsereg-master/example/
  2. python sindy.py
### In cmd
  1. cd to '../sparsereg-master/example/
  2. python sindy.py

## Specifications

  - Version: 0.6.3
  - Platform: Windows 10
  - Subsystem: ipython, powershell, and cmd

**Comment by Ohjeah** [comment]
What's you version of sklearn?

**Comment by Ohjeah** [comment]
Fixed in ed04f102af845de08f107b97b08f4a31cc8fb72c. Thanks for the report.
